### ISSUE TITLE
LORA runtimeerror

### ISSUE THREAD

**Issue by Jyerim** [LaVi-Lab/Video-3D-LLM#3]
Hi,
I encountered an error message when training the model with LORA.
How can I fix this issue? 
Are there any known compatibility problems or additional configurations required for using Lora with DeepSpeed?
Any guidance would be greatly appreciated.
The training stops at step 500 with the following error:

`Traceback (most recent call last):
  File "/workspace/About_3DReason/Video-3D-LLM/llava/train/train_3d.py", line 1867, in train
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1806, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2150, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3077, in training_step
    self.accelerator.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2151, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 166, in backward
    self.engine.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1967, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2213, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 358, in backward
    ctx.pre_backward_function(ctx.module)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 339, in _run_before_backward_function
    self.pre_sub_module_backward_function(sub_module)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 474, in pre_sub_module_backward_function
    param_coordinator.fetch_sub_module(sub_module, forward=False)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 339, in fetch_sub_module
    raise RuntimeError(
RuntimeError: tracing error at step 1556: 
module id: 1, training: True
expected the next 1 parameters in the parameter fetch queue to be ({'id': 'name=base_model.model.ground_head_zero_target id=1143', 'status': 'AVAILABLE', 'numel': 3584, 'ds_numel': 3584, 'shape': (3584,), 'ds_shape': (3584,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {1}, 'ds_tensor.shape': torch.Size([896])},) 
but got 
 ({'id': 'name=base_model.model.model.layers.19.mlp.gate_proj.lora_A.default.weight id=1419', 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 229376, 'shape': (0,), 'ds_shape': (64, 3584), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([57344])},).`

**Comment by zd11024** [comment]
Sorry, I just retried the training script and didn't get this error. Could you please check your environment setup again?

**Comment by zd11024** [comment]
This issue will be closed for now. Please feel free to reopen it if needed.

**Comment by Mq-Zhang1** [comment]
Hi
I have met exactly the same problem. The environment is installed following readme. Have you found the solution?

**Comment by zd11024** [comment]
Sorry, we have not found the reason for this error. We recommend that you finetune the entire model according to the method in our paper.
